### ISSUE TITLE
Не запускаеться на Windiws

### ISSUE THREAD

**Issue by EndrII** [EndrII/AlcoParty#8]
При запуске приложение пытается развернуть ноду в локальной сети с не верным ip  адресом.
программа получает свой IP адрес в методе:<br> `LocalScanner::thisAdress()` файл` LocalScanner`<br>.
Свой настоящий ip можно посмотреть в `СMD ipconfig `

**Comment by usermeme** [comment]
Готово, изменение в https://github.com/EndrII/AlcoParty/pull/9
